# Tutorial to download (and save) PFAS-data from DOV through pydov

In [1]:
import os
os.environ['PYDOV_BASE_URL'] = 'https://oefen.dov.vlaanderen.be'

from PFAS_concentrations import RequestPFASdata
from pydov.util.location import Within, Box

/home/roel/Work/DOV/pydov/Code/pydov/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Check out the query and customization options from pydov.\
You can query on [location](https://pydov.readthedocs.io/en/stable/query_location.html) and also [restrict the number of WFS features returned](https://pydov.readthedocs.io/en/stable/sort_limit.html).

## Case 1 : You want to save the data

### Example 1 : You want to download and save all the PFAS data of Flanders

In [2]:
medium = ['all']
location = Within(Box(15000, 150000, 270000, 250000, epsg=31370))  # Bounding box Flanders

rd = RequestPFASdata()
df = rd.main(medium, location=location, max_features=None, save=True)[0]

2026-02-06 14:28:46.734 | INFO     | PFAS_concentrations:biota:441 - Downloading biota data

[000/001] .

2026-02-06 14:28:49.728 | INFO     | PFAS_concentrations:effluent:479 - Downloading effluent data

[000/001] .

2026-02-06 14:28:56.777 | INFO     | PFAS_concentrations:groundwater:520 - Downloading groundwater data

[000/001] .
[000/001] .
[000/001] .
[000/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[050/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[100/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[150/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[200/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[250/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[300/347] ccccccccccccccccccccccccccccccccccccccccccccccc
[000/001] .
[000/001] .

2026-02-06 14:33:58.516 | INFO     | PFAS_concentrations:migration:581 - Downloading migration data

[000/001] .

2026-02-06 14:34:04.282 | INFO     | PFAS_concentrations:pure_product:628 - Downloading pure product data

[000/001] .

2026-02-06 14:34:09.654 | INFO     | PFAS_concentrations:rainwater:675 - Downloading rainwater data

[000/001] .

2026-02-06 14:34:14.880 | INFO     | PFAS_concentrations:soil:716 - Downloading soil data

[000/001] .
[000/001] .

/home/roel/Work/DOV/pydov/Code/pydov/contrib/PFAS_concentrations/PFAS_concentrations.py:326: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["pkey_diepteinterval"] = df["pkey_diepteinterval"].fillna(

[000/001] .
[000/002] ..
[000/001] .

2026-02-06 14:40:58.306 | INFO     | PFAS_concentrations:soil_water:784 - Downloading soilwater data

[000/001] .

2026-02-06 14:41:07.276 | INFO     | PFAS_concentrations:surface_water:844 - Downloading surface water data

[000/001] .
[000/001] .

2026-02-06 14:41:43.098 | INFO     | PFAS_concentrations:waste_water:896 - Downloading waste water data

[000/001] .

2026-02-06 14:42:23.095 | INFO     | PFAS_concentrations:air:931 - Downloading air data

[000/001] .
[000/001] .
[000/001] .

100%|██████████| 4789729/4789729 [06:56<00:00, 11506.52it/s]
2026-02-06 14:50:16.542 | INFO     | PFAS_concentrations:main:1665 - The program was executed in 0:21:29.808442.

### Example 2 : You only want to download and save the groundwater data of Flanders

In [5]:
medium = ['groundwater']
location = Within(Box(15000, 150000, 270000, 250000, epsg=31370))  # Bounding box Flanders

rd = RequestPFASdata()
df = rd.main(medium, location=location, max_features=None, save=True)[0]

2026-02-06 15:08:16.596 | INFO     | PFAS_concentrations:groundwater:520 - Downloading groundwater data

[000/001] .
[000/001] .
[000/001] .
[000/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[050/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[100/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[150/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[200/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[250/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[300/347] ccccccccccccccccccccccccccccccccccccccccccccccc
[000/001] .
[000/001] .

100%|██████████| 951050/951050 [01:55<00:00, 8207.82it/s]
2026-02-06 15:15:51.357 | INFO     | PFAS_concentrations:main:1665 - The program was executed in 0:07:34.760517.

### Example 3 : You want to download and save the soil and groundwater data of Flanders

In [6]:
medium = ['soil', 'groundwater']
location = Within(Box(15000, 150000, 270000, 250000, epsg=31370))  # Bounding box Flanders

rd = RequestPFASdata()
df = rd.main(medium, location=location, max_features=None, save=True)[0]

2026-02-06 15:22:57.628 | INFO     | PFAS_concentrations:soil:716 - Downloading soil data

[000/001] .
[000/001] .

/home/roel/Work/DOV/pydov/Code/pydov/contrib/PFAS_concentrations/PFAS_concentrations.py:326: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["pkey_diepteinterval"] = df["pkey_diepteinterval"].fillna(

[000/001] .
[000/002] ..
[000/001] .

2026-02-06 15:30:16.951 | INFO     | PFAS_concentrations:groundwater:520 - Downloading groundwater data

[000/001] .
[000/001] .
[000/001] .
[000/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[050/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[100/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[150/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[200/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[250/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[300/347] ccccccccccccccccccccccccccccccccccccccccccccccc
[000/001] .
[000/001] .

100%|██████████| 2106106/2106106 [04:26<00:00, 7889.40it/s]
2026-02-06 15:40:38.839 | INFO     | PFAS_concentrations:main:1665 - The program was executed in 0:17:41.211241.

### Example 4 : You want to download and save the combined groundwater PFAS data of Flanders

In [7]:
medium = ['combined_groundwater']
location = Within(Box(15000, 150000, 270000, 250000, epsg=31370))  # Bounding box Flanders

rd = RequestPFASdata()
df = rd.main(medium, location=location, max_features=None, save=True)[0]

2026-02-06 15:44:01.119 | INFO     | PFAS_concentrations:groundwater:520 - Downloading groundwater data

[000/001] .
[000/001] .
[000/001] .
[000/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[050/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[100/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[150/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[200/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[250/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[300/347] ccccccccccccccccccccccccccccccccccccccccccccccc
[000/001] .
[000/001] .

100%|██████████| 951050/951050 [01:29<00:00, 10571.54it/s]
2026-02-06 15:51:47.237 | INFO     | PFAS_concentrations:main:1665 - The program was executed in 0:07:46.119360.

## Case 2 : You want the data in a dataframe to integrate it in your python script

### Example 1 : You want to download all the PFAS data of Flanders

In [8]:
medium = ['all']
location = Within(Box(15000, 150000, 270000, 250000, epsg=31370))  # Bounding box Flanders
rd = RequestPFASdata()
df = rd.main(medium, location=location, max_features=None)[0]

2026-02-06 16:08:25.925 | INFO     | PFAS_concentrations:biota:441 - Downloading biota data

[000/001] .

2026-02-06 16:08:29.062 | INFO     | PFAS_concentrations:effluent:479 - Downloading effluent data

[000/001] .

2026-02-06 16:08:35.762 | INFO     | PFAS_concentrations:groundwater:520 - Downloading groundwater data

[000/001] .
[000/001] .
[000/001] .
[000/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[050/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[100/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[150/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[200/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[250/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[300/347] ccccccccccccccccccccccccccccccccccccccccccccccc
[000/001] .
[000/001] .

2026-02-06 16:14:57.676 | INFO     | PFAS_concentrations:migration:581 - Downloading migration data

[000/001] .

2026-02-06 16:15:06.996 | INFO     | PFAS_concentrations:pure_product:628 - Downloading pure product data

[000/001] .

2026-02-06 16:15:35.953 | INFO     | PFAS_concentrations:rainwater:675 - Downloading rainwater data

[000/001] .

2026-02-06 16:15:58.696 | INFO     | PFAS_concentrations:soil:716 - Downloading soil data

[000/001] .
[000/001] .

/home/roel/Work/DOV/pydov/Code/pydov/contrib/PFAS_concentrations/PFAS_concentrations.py:326: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["pkey_diepteinterval"] = df["pkey_diepteinterval"].fillna(

[000/001] .
[000/002] ..
[000/001] .

2026-02-06 16:23:08.493 | INFO     | PFAS_concentrations:soil_water:784 - Downloading soilwater data

[000/001] .

2026-02-06 16:23:19.423 | INFO     | PFAS_concentrations:surface_water:844 - Downloading surface water data

[000/001] .
[000/001] .

2026-02-06 16:23:55.992 | INFO     | PFAS_concentrations:waste_water:896 - Downloading waste water data

[000/001] .

2026-02-06 16:24:35.404 | INFO     | PFAS_concentrations:air:931 - Downloading air data

[000/001] .
[000/001] .
[000/001] .

2026-02-06 16:25:42.136 | INFO     | PFAS_concentrations:main:1665 - The program was executed in 0:17:16.210015.

In [9]:
# Biota_VMM
df[0].info()
df[0].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2627 entries, 0 to 2626
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                2627 non-null   int64
 1   meetplaats        2627 non-null   object
 2   x_mL72            2627 non-null   int64
 3   y_mL72            2627 non-null   int64
 4   jaar              2627 non-null   int64
 5   datum             2627 non-null   object
 6   parameter         2627 non-null   object
 7   detectieconditie  2627 non-null   object
 8   meetwaarde        2627 non-null   float64
 9   meeteenheid       2627 non-null   object
 10  omschrijving      2599 non-null   object
 11  vha_segment_code  2627 non-null   int64
dtypes: float64(1), int64(5), object(6)
memory usage: 246.4+ KB

,id,meetplaats,x_mL72,y_mL72,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,omschrijving,vha_segment_code
0,1,12000,104330,218850,2020,2020-07-13,PFOS,=,2.300,µg/kg ng,"Philippine,Isabellahaven,Dijckmeesterweg",6019988
1,2,12000,104330,218850,2020,2020-07-13,PFOS,=,1.490,µg/kg ng,"Philippine,Isabellahaven,Dijckmeesterweg",6019988
2,3,12000,104330,218850,2020,2020-07-13,PFOS,=,2.400,µg/kg ng,"Philippine,Isabellahaven,Dijckmeesterweg",6019988
3,4,12000,104330,218850,2016,2016-10-14,PFBA,<,0.135,µg/kg ng,"Philippine,Isabellahaven,Dijckmeesterweg",6019988
4,5,12000,104330,218850,2016,2016-10-14,PFDA,<,0.824,µg/kg ng,"Philippine,Isabellahaven,Dijckmeesterweg",6019988

In [10]:
# Effluent_OVAM
df[1].info()
df[1].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2646 entries, 0 to 2645
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2646 non-null   int64
 1   opdracht           2646 non-null   int64
 2   pfasdossiernr      2646 non-null   int64
 3   profielnaam        2646 non-null   object
 4   top_in_m           2056 non-null   float64
 5   basis_in_m         2056 non-null   float64
 6   jaar               2646 non-null   int64
 7   datum              2646 non-null   object
 8   parameter          2646 non-null   object
 9   detectieconditie   2646 non-null   object
 10  meetwaarde         2646 non-null   float64
 11  meeteenheid        2646 non-null   object
 12  medium             2646 non-null   object
 13  profieltype        2646 non-null   object
 14  plaatsing_profiel  2553 non-null   object
 15  commentaar         2646 non-null   object
 16  x_ml72             2646 non-null   float64
 17  y_ml72             2646 non-null   float64
dtypes: float64(5), int64(4), object(9)
memory usage: 372.2+ KB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,31426742,13269077,732,Effluent WWTP,0.0,0.0,2019,2019-07-31,PFHxStotaal,<,0.152,µg/l,Effluent,Staal,NaN,,147811.54,213425.03
1,31426743,13269077,732,Effluent WWTP,0.0,0.0,2019,2019-07-31,PFOAtotaal,<,0.252,µg/l,Effluent,Staal,NaN,,147811.54,213425.03
2,31426744,13269077,732,Effluent WWTP,0.0,0.0,2019,2019-07-31,PFOSAtotaal,<,0.256,µg/l,Effluent,Staal,NaN,,147811.54,213425.03
3,31426745,13269077,732,Effluent WWTP,0.0,0.0,2019,2019-07-31,PFOStotaal,<,0.185,µg/l,Effluent,Staal,NaN,,147811.54,213425.03
4,31426746,13269077,732,Effluent WWTP,0.0,0.0,2019,2019-04-25,PFOSAtotaal,=,0.223,µg/l,Effluent,Staal,NaN,,147811.54,213425.03

In [31]:
# Groundwater_pydov
df[2].info()
df[2].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12921 entries, 0 to 12920
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pkey_monster             12921 non-null  object
 1   parametergroep           12921 non-null  object
 2   parameter                12921 non-null  object
 3   detectie                 11354 non-null  object
 4   waarde                   12921 non-null  object
 5   eenheid                  12921 non-null  object
 6   methode                  12921 non-null  object
 7   datum_monstername        12921 non-null  datetime64[ns]
 8   pkey_parents             12921 non-null  object
 9   grondwatermonsternummer  12921 non-null  object
 10  pkey_filter              12921 non-null  object
 11  aquifer_code             12921 non-null  object
 12  diepte_onderkant_filter  12104 non-null  float64
 13  lengte_filter            12104 non-null  float64
 14  x                        12921 non-null  float64
 15  y                        12921 non-null  float64
 16  top_m_mv                 12104 non-null  float64
dtypes: datetime64[ns](1), float64(5), object(11)
memory usage: 1.7+ MB

,pkey_monster,parametergroep,parameter,detectie,waarde,eenheid,methode,datum_monstername,pkey_parents,grondwatermonsternummer,pkey_filter,aquifer_code,diepte_onderkant_filter,lengte_filter,x,y,top_m_mv
0,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,perfluor-n-octaanzuur vertakt (PFOAbranched) (...,<,1,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9,2.0
1,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,perfluorheptaansulfonzuur (PFHpS) (PFHpS),<,1,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9,2.0
2,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,perfluor-4-ethylcyclohexaansulfonzuur (PFECHS)...,<,1,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9,2.0
3,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,6:2/8:2 fluortelomeerfosfaat diester (6:2/8:2 ...,<,10,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9,2.0
4,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,totaal perfluor-n-octaanzuur (lineair + vertak...,NaN,2,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9,2.0

In [12]:
# Groundwater_OVAM
df[3].info()
df[3].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 932534 entries, 0 to 932533
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 932534 non-null  int64
 1   opdracht           932534 non-null  int64
 2   pfasdossiernr      932534 non-null  int64
 3   profielnaam        932534 non-null  object
 4   top_in_m           921853 non-null  float64
 5   basis_in_m         921853 non-null  float64
 6   jaar               932534 non-null  int64
 7   datum              932534 non-null  object
 8   parameter          932534 non-null  object
 9   detectieconditie   932534 non-null  object
 10  meetwaarde         932534 non-null  float64
 11  meeteenheid        932397 non-null  object
 12  medium             932534 non-null  object
 13  profieltype        932534 non-null  object
 14  plaatsing_profiel  887892 non-null  object
 15  commentaar         932534 non-null  object
 16  x_ml72             932534 non-null  float64
 17  y_ml72             932534 non-null  float64
dtypes: float64(5), int64(4), object(9)
memory usage: 128.1+ MB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,31063070,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFHpS,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
1,31063071,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFBS,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
2,31063072,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,HFPO-DA,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
3,31063073,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFODA,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
4,31063074,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFBA,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0

In [13]:
# Groundwater_Lantis
df[4].info()
df[4].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5595 entries, 0 to 5594
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectdeel         5595 non-null   object
 1   peilbuis            5595 non-null   object
 2   filter_van_m        4778 non-null   float64
 3   filter_tot_m        5122 non-null   float64
 4   nummer              5595 non-null   int64
 5   analysemonster      5595 non-null   object
 6   datum_bemonstering  5595 non-null   object
 7   gegevens            5595 non-null   object
 8   parameter           5595 non-null   object
 9   detectieconditie    5595 non-null   object
 10  waarde              5595 non-null   float64
 11  eenheid             5595 non-null   object
 12  x_ml72              5595 non-null   float64
 13  y_ml72              5595 non-null   float64
dtypes: float64(5), int64(1), object(8)
memory usage: 612.1+ KB

,projectdeel,peilbuis,filter_van_m,filter_tot_m,nummer,analysemonster,datum_bemonstering,gegevens,parameter,detectieconditie,waarde,eenheid,x_ml72,y_ml72
0,R1O1,PBC3,NaN,14.9,182,PBC3,2022/02/04,RoTS/WiBo,PFHxS,=,5.0,ng/l,154735.956833,213286.10449
1,R1O1,P406,4.1,6.1,88,LD_406,2021/09/23,RoTS/WiBo,8:2 FTS,<,2.0,ng/l,154457.340000,213702.00000
2,KZ,StadAnt_280,3.4,4.4,248,StadAnt_280-1-1 StadAnt_280,2022/01/25,RoTS/Sweco,PFHxDA,<,1.0,ng/l,152803.809990,214595.20000
3,R1O1,P402a,9.1,10.1,77,LD_402a,2021/08/19,RoTS/WiBo,10:2 FTS,<,4.0,ng/l,154374.470000,213884.06000
4,STLO,PFAS-Diep-PB5,21.0,23.0,195,PFAS-Diep-PB5-1-2 PFAS-Diep-PB5,2021/12/08,RoTS/Sweco,PFHxDA,<,1.0,ng/l,149800.908600,214023.70810

In [14]:
# Migration_OVAM
df[5].info()
df[5].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 480 non-null    int64
 1   opdracht           480 non-null    int64
 2   pfasdossiernr      480 non-null    int64
 3   profielnaam        480 non-null    object
 4   top_in_m           480 non-null    float64
 5   basis_in_m         480 non-null    float64
 6   jaar               480 non-null    int64
 7   datum              480 non-null    object
 8   parameter          480 non-null    object
 9   detectieconditie   480 non-null    object
 10  meetwaarde         480 non-null    float64
 11  meeteenheid        480 non-null    object
 12  medium             480 non-null    object
 13  profieltype        480 non-null    object
 14  plaatsing_profiel  480 non-null    object
 15  commentaar         480 non-null    object
 16  x_ml72             480 non-null    float64
 17  y_ml72             480 non-null    float64
dtypes: float64(5), int64(4), object(9)
memory usage: 67.6+ KB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,32502917,13777505,98809,Volkstuinlekkeroever bosbes ongewassen,0.0,0.1,2021,2021-09-02,PFHxDA,<,1.00,µg/kg,Migratie,Staal,2021-09-02,,151127.0,212951.0
1,32502918,13777505,98809,Volkstuinlekkeroever bosbes ongewassen,0.0,0.1,2021,2021-09-02,PFOSAtotaal,<,0.10,µg/kg,Migratie,Staal,2021-09-02,,151127.0,212951.0
2,32502919,13777505,98809,Volkstuinlekkeroever bosbes ongewassen,0.0,0.1,2021,2021-09-02,PFDA,<,0.10,µg/kg,Migratie,Staal,2021-09-02,,151127.0,212951.0
3,32502920,13777505,98809,Volkstuinlekkeroever bosbes ongewassen,0.0,0.1,2021,2021-09-02,8:2 FTS,<,0.30,µg/kg,Migratie,Staal,2021-09-02,,151127.0,212951.0
4,32502921,13777505,98809,Volkstuinlekkeroever bosbes ongewassen,0.0,0.1,2021,2021-09-02,PFBA,=,6.78,µg/kg,Migratie,Staal,2021-09-02,,151127.0,212951.0

In [15]:
# Pure_product_OVAM
df[6].info()
df[6].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1088 entries, 0 to 1087
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1088 non-null   int64
 1   opdracht           1088 non-null   int64
 2   pfasdossiernr      1088 non-null   int64
 3   profielnaam        1088 non-null   object
 4   top_in_m           1061 non-null   float64
 5   basis_in_m         1061 non-null   float64
 6   jaar               1088 non-null   int64
 7   datum              1088 non-null   object
 8   parameter          1088 non-null   object
 9   detectieconditie   1088 non-null   object
 10  meetwaarde         1088 non-null   float64
 11  meeteenheid        1088 non-null   object
 12  medium             1088 non-null   object
 13  profieltype        1088 non-null   object
 14  plaatsing_profiel  1088 non-null   object
 15  commentaar         1088 non-null   object
 16  x_ml72             1088 non-null   float64
 17  y_ml72             1088 non-null   float64
dtypes: float64(5), int64(4), object(9)
memory usage: 153.1+ KB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,32936065,14048724,97883,S02,3.0,3.2,2022,2022-05-27,PFTeDA,<,0.47,µg/kg ds,Puur product,Waterbodemstaal,2022-04-27,,166758.0,205647.0
1,32936066,14048724,97883,S02,3.0,3.2,2022,2022-05-27,4:2 FTS,<,0.47,µg/kg ds,Puur product,Waterbodemstaal,2022-04-27,,166758.0,205647.0
2,32936067,14048724,97883,S02,3.0,3.2,2022,2022-05-27,PFNS,<,0.47,µg/kg ds,Puur product,Waterbodemstaal,2022-04-27,,166758.0,205647.0
3,32936068,14048724,97883,S02,3.0,3.2,2022,2022-05-27,PFAS Som indicatief,<,2.82,µg/kg ds,Puur product,Waterbodemstaal,2022-04-27,,166758.0,205647.0
4,32936069,14048724,97883,S02,3.0,3.2,2022,2022-05-27,MePFOSAtotaal,<,0.47,µg/kg ds,Puur product,Waterbodemstaal,2022-04-27,,166758.0,205647.0

In [16]:
# Rainwater_OVAM
df[7].info()
df[7].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 150 non-null    int64
 1   opdracht           150 non-null    int64
 2   pfasdossiernr      150 non-null    int64
 3   profielnaam        150 non-null    object
 4   top_in_m           95 non-null     float64
 5   basis_in_m         95 non-null     float64
 6   jaar               150 non-null    int64
 7   datum              150 non-null    object
 8   parameter          150 non-null    object
 9   detectieconditie   150 non-null    object
 10  meetwaarde         150 non-null    float64
 11  meeteenheid        150 non-null    object
 12  medium             150 non-null    object
 13  profieltype        150 non-null    object
 14  plaatsing_profiel  55 non-null     object
 15  commentaar         150 non-null    object
 16  x_ml72             150 non-null    float64
 17  y_ml72             150 non-null    float64
dtypes: float64(5), int64(4), object(9)
memory usage: 21.2+ KB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,31427010,13269077,732,Collector pit,0.0,0.0,2018,2018-07-10,PFHxStotaal,=,19.20,µg/l,Regenwater,Staal,NaN,,147744.05,213419.4
1,31427011,13269077,732,Collector pit,0.0,0.0,2018,2018-07-10,PFOStotaal,=,203.00,µg/l,Regenwater,Staal,NaN,,147744.05,213419.4
2,31427012,13269077,732,Collector pit,0.0,0.0,2018,2018-07-10,PFOStotaal,=,176.00,µg/l,Regenwater,Staal,NaN,,147744.05,213419.4
3,31427013,13269077,732,Collector pit,0.0,0.0,2018,2018-07-10,PFOSAtotaal,=,14.40,µg/l,Regenwater,Staal,NaN,,147744.05,213419.4
4,31427014,13269077,732,Collector pit,0.0,0.0,2018,2018-07-10,PFOSAtotaal,=,8.31,µg/l,Regenwater,Staal,NaN,,147744.05,213419.4

In [32]:
# Soil_pydov
df[8].info()
df[8].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2353 entries, 0 to 2352
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2353 non-null   object
 1   pkey_parent          2353 non-null   object
 2   parametergroep       2353 non-null   object
 3   parameter            2353 non-null   object
 4   detectieconditie     2201 non-null   object
 5   meetwaarde           2353 non-null   object
 6   eenheid              2353 non-null   object
 7   methode              2353 non-null   object
 8   datum                2353 non-null   object
 9   diepte_van_m         1 non-null      float64
 10  diepte_tot_m         2 non-null      float64
 11  pkey_bodemlocatie    1 non-null      object
 12  pkey_monster         2351 non-null   object
 13  pkey_diepteinterval  0 non-null      float64
 14  x_m_L72              1 non-null      float64
 15  y_m_L72              1 non-null      float64
 16  naam                 1 non-null      object
dtypes: float64(5), object(12)
memory usage: 312.6+ KB

,id,pkey_parent,parametergroep,parameter,detectieconditie,meetwaarde,eenheid,methode,datum,diepte_van_m,diepte_tot_m,pkey_bodemlocatie,pkey_monster,pkey_diepteinterval,x_m_L72,y_m_L72,naam
0,observatie/2023-37798791,monster/2023-376712,Bodem_chemisch_PFAS,perfluornonaansulfonzuur (PFNS) (PFNS),<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN
1,observatie/2023-37798785,monster/2023-376712,Bodem_chemisch_PFAS,perfluorhexaanzuur (PFHxA) (PFHxA),<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN
2,observatie/2023-37798770,monster/2023-376712,Bodem_chemisch_PFAS,N-methylperfluorbutaansulfonamide (MePFBSA) (M...,<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN
3,observatie/2023-37798774,monster/2023-376712,Bodem_chemisch_PFAS,N-methylperfluorbutaansulfonylamide azijnzuur ...,<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN
4,observatie/2023-37798786,monster/2023-376712,Bodem_chemisch_PFAS,perfluorhexadecaanzuur (PFHxDA) (PFHxDA),<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN

In [ ]:
# Soil_OVAM
df[9].info()
df[9].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003099 entries, 0 to 1003098
Data columns (total 18 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id                 1003099 non-null  int64
 1   opdracht           1003099 non-null  int64
 2   pfasdossiernr      1003099 non-null  int64
 3   profielnaam        1003099 non-null  object
 4   top_in_m           1003099 non-null  float64
 5   basis_in_m         1003099 non-null  float64
 6   jaar               1003099 non-null  int64
 7   datum              1003099 non-null  object
 8   parameter          1003099 non-null  object
 9   detectieconditie   1003099 non-null  object
 10  meetwaarde         1003099 non-null  float64
 11  meeteenheid        1003099 non-null  object
 12  medium             1003099 non-null  object
 13  profieltype        1003099 non-null  object
 14  plaatsing_profiel  937826 non-null   object
 15  commentaar         1003099 non-null  object
 16  x_ml72             1003099 non-null  float64
 17  y_ml72             1003099 non-null  float64
dtypes: float64(5), int64(4), object(9)
memory usage: 137.8+ MB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,31063144,13077062,6180,108,0.5,0.7,2021,2021-06-01,PFHxStotaal,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0
1,31063147,13077062,6180,108,0.5,0.7,2021,2021-06-01,PFPeA,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0
2,31063151,13077062,6180,108,0.5,0.7,2021,2021-06-01,8:2 diPAP,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0
3,31063157,13077062,6180,108,0.5,0.7,2021,2021-06-01,PFPeS,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0
4,31063159,13077062,6180,108,0.5,0.7,2021,2021-06-01,PFNS,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0

In [ ]:
# Soil_Lantis
df[10].info()
df[10].head()

<class 'pandas.core.frame.DataFrame'>
Index: 149604 entries, 0 to 153055
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   boring              149604 non-null  object
 1   diepte_van_m        149576 non-null  float64
 2   diepte_tot_m        149386 non-null  float64
 3   unieke_monstercode  149604 non-null  object
 4   analysemonster      149604 non-null  object
 5   datum_bemonstering  147731 non-null  object
 6   gegevens            149604 non-null  object
 7   parameter           149604 non-null  object
 8   detectieconditie    149604 non-null  object
 9   waarde              149604 non-null  float64
 10  eenheid             149604 non-null  object
 11  x_ml72              149604 non-null  object
 12  y_ml72              149604 non-null  object
dtypes: float64(3), object(10)
memory usage: 16.0+ MB

,boring,diepte_van_m,diepte_tot_m,unieke_monstercode,analysemonster,datum_bemonstering,gegevens,parameter,detectieconditie,waarde,eenheid,x_ml72,y_ml72
0,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,totaal PFAS,=,0.0,µg/kg ds,148378.16,211294.01
1,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,totaal PFAS kwantitatief,<,0.5,µg/kg ds,148378.16,211294.01
2,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,totaal PFAS indicatief,<,1.0,µg/kg ds,148378.16,211294.01
3,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,som PFOA,<,0.5,µg/kg ds,148378.16,211294.01
4,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,som PFOS,<,0.5,µg/kg ds,148378.16,211294.01

In [ ]:
# Soil_water_VMM
df[11].info()
df[11].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Soil_water_OVAM
df[12].info()
df[12].head()

<class 'pandas.core.frame.DataFrame'>
Index: 14416 entries, 0 to 15118
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 14416 non-null  int64
 1   opdracht           14416 non-null  int64
 2   pfasdossiernr      14416 non-null  int64
 3   profielnaam        14416 non-null  object
 4   top_in_m           14194 non-null  float64
 5   basis_in_m         14194 non-null  float64
 6   jaar               14416 non-null  int64
 7   datum              14416 non-null  object
 8   parameter          14416 non-null  object
 9   detectieconditie   14416 non-null  object
 10  meetwaarde         14416 non-null  float64
 11  meeteenheid        14416 non-null  object
 12  medium             14416 non-null  object
 13  profieltype        14416 non-null  object
 14  plaatsing_profiel  12697 non-null  object
 15  commentaar         14416 non-null  object
 16  x_ml72             14416 non-null  float64
 17  y_ml72             14416 non-null  float64
dtypes: float64(5), int64(4), object(9)
memory usage: 2.1+ MB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,32157495,13617019,732,ERM686,0.0,0.1,2021,2021-10-08,PFNS,<,0.20,µg/kg ds,Waterbodem - sediment,Boring,2021-09-28,,146312.81,213203.76
1,32157496,13617019,732,ERM686,0.0,0.1,2021,2021-10-08,PFBA,=,0.82,µg/kg ds,Waterbodem - sediment,Boring,2021-09-28,,146312.81,213203.76
2,32157497,13617019,732,ERM686,0.0,0.1,2021,2021-10-08,PFBSA,<,0.20,µg/kg ds,Waterbodem - sediment,Boring,2021-09-28,,146312.81,213203.76
3,32157498,13617019,732,ERM686,0.0,0.1,2021,2021-10-08,6:2 FTS,<,0.21,µg/kg ds,Waterbodem - sediment,Boring,2021-09-28,,146312.81,213203.76
4,32157499,13617019,732,ERM686,0.0,0.1,2021,2021-10-08,PFDoDS,<,0.32,µg/kg ds,Waterbodem - sediment,Boring,2021-09-28,,146312.81,213203.76

In [ ]:
# Soil_water_OVAM
df[13].info()
df[13].head()

<class 'pandas.core.frame.DataFrame'>
Index: 813 entries, 336 to 15228
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 813 non-null    int64
 1   opdracht           813 non-null    int64
 2   pfasdossiernr      813 non-null    int64
 3   profielnaam        813 non-null    object
 4   top_in_m           813 non-null    float64
 5   basis_in_m         813 non-null    float64
 6   jaar               813 non-null    int64
 7   datum              813 non-null    object
 8   parameter          813 non-null    object
 9   detectieconditie   813 non-null    object
 10  meetwaarde         813 non-null    float64
 11  meeteenheid        813 non-null    object
 12  medium             813 non-null    object
 13  profieltype        813 non-null    object
 14  plaatsing_profiel  813 non-null    object
 15  commentaar         813 non-null    object
 16  x_ml72             813 non-null    float64
 17  y_ml72             813 non-null    float64
dtypes: float64(5), int64(4), object(9)
memory usage: 120.7+ KB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
336,33518013,14336493,98122,Sch3,0.0,0.15,2022,2022-08-19,PFNS,<,0.47,µg/kg ds,Waterbodem - vaste deel van waterbodem,Boring,2022-08-12,,156833.0,232877.0
337,33518014,14336493,98122,Sch3,0.0,0.15,2022,2022-08-19,MePFBSAA,<,0.47,µg/kg ds,Waterbodem - vaste deel van waterbodem,Boring,2022-08-12,,156833.0,232877.0
338,33518015,14336493,98122,Sch3,0.0,0.15,2022,2022-08-19,PFTrDA,<,0.47,µg/kg ds,Waterbodem - vaste deel van waterbodem,Boring,2022-08-12,,156833.0,232877.0
339,33518016,14336493,98122,Sch3,0.0,0.15,2022,2022-08-19,8:2 diPAP,<,0.47,µg/kg ds,Waterbodem - vaste deel van waterbodem,Boring,2022-08-12,,156833.0,232877.0
340,33518017,14336493,98122,Sch3,0.0,0.15,2022,2022-08-19,PFODA,<,2.80,µg/kg ds,Waterbodem - vaste deel van waterbodem,Boring,2022-08-12,,156833.0,232877.0

In [ ]:
# Surface_water_VMM
df[14].info()
df[14].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92455 entries, 0 to 92454
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ogc_fid           92455 non-null  int64
 1   meetplaats        92455 non-null  int64
 2   x_mL72            92455 non-null  int64
 3   y_mL72            92455 non-null  int64
 4   jaar              92455 non-null  int64
 5   datum             92455 non-null  object
 6   parameter         92455 non-null  object
 7   detectieconditie  92455 non-null  object
 8   meetwaarde        92455 non-null  float64
 9   meeteenheid       92455 non-null  object
 10  omschrijving      92455 non-null  object
 11  vha_segment_code  92455 non-null  int64
dtypes: float64(1), int64(6), object(5)
memory usage: 8.5+ MB

,ogc_fid,meetplaats,x_mL72,y_mL72,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,omschrijving,vha_segment_code
0,10213,162000,147328,203675,2007,2007-05-31,PFNA,=,11.0,ng/l,"Kallebeekstraat, thv veerpont Hemiksem - Kruib...",6018692
1,10214,162000,147328,203675,2007,2007-05-31,PFOA,=,169.0,ng/l,"Kallebeekstraat, thv veerpont Hemiksem - Kruib...",6018692
2,5931,154100,141077,227033,2007,2007-05-31,PFHpA,=,45.0,ng/l,"Zandvliet, grens Doel; vaargeul midden Schelde...",6033846
3,5932,154100,141077,227033,2007,2007-05-31,PFNA,=,8.0,ng/l,"Zandvliet, grens Doel; vaargeul midden Schelde...",6033846
4,5933,154100,141077,227033,2007,2007-05-31,PFOA,=,721.0,ng/l,"Zandvliet, grens Doel; vaargeul midden Schelde...",6033846

In [ ]:
# Surface_water_OVAM
df[15].info()
df[15].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24651 entries, 0 to 24650
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 24651 non-null  int64
 1   opdracht           24651 non-null  int64
 2   pfasdossiernr      24651 non-null  int64
 3   profielnaam        24651 non-null  object
 4   top_in_m           12105 non-null  float64
 5   basis_in_m         12105 non-null  float64
 6   jaar               24651 non-null  int64
 7   datum              24651 non-null  object
 8   parameter          24651 non-null  object
 9   detectieconditie   24651 non-null  object
 10  meetwaarde         24651 non-null  float64
 11  meeteenheid        24651 non-null  object
 12  medium             24651 non-null  object
 13  profieltype        24651 non-null  object
 14  plaatsing_profiel  20942 non-null  object
 15  commentaar         24651 non-null  object
 16  x_ml72             24651 non-null  float64
 17  y_ml72             24651 non-null  float64
dtypes: float64(5), int64(4), object(9)
memory usage: 3.4+ MB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,31427456,13269077,732,12,0.0,0.0,2018,2018-07-09,PFHxStotaal,=,34.600,µg/l,Oppervlaktewater,Staal,NaN,,147674.05,213145.33
1,31427457,13269077,732,12,0.0,0.0,2018,2018-07-09,PFOStotaal,=,449.000,µg/l,Oppervlaktewater,Staal,NaN,,147674.05,213145.33
2,31427458,13269077,732,12,0.0,0.0,2018,2018-07-09,PFOAtotaal,=,121.000,µg/l,Oppervlaktewater,Staal,NaN,,147674.05,213145.33
3,31427459,13269077,732,12,0.0,0.0,2018,2018-07-09,PFOSAtotaal,=,0.655,µg/l,Oppervlaktewater,Staal,NaN,,147674.05,213145.33
4,31427460,13269077,732,12,0.0,0.0,2018,2018-01-22,PFHxStotaal,=,9.850,µg/l,Oppervlaktewater,Staal,NaN,,147674.05,213145.33

In [ ]:
# Waste_water_VMM
df[16].info()
df[16].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125655 entries, 0 to 125654
Data columns (total 20 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ogc_fid                    125655 non-null  int64
 1   bedrijfsnaam               125655 non-null  object
 2   id                         125655 non-null  int64
 3   meetplaats                 125655 non-null  int64
 4   x_mL72                     125655 non-null  int64
 5   y_mL72                     125655 non-null  int64
 6   jaar                       125655 non-null  int64
 7   datum                      125655 non-null  object
 8   parameter                  125655 non-null  object
 9   detectieconditie           125655 non-null  object
 10  meetwaarde                 125655 non-null  float64
 11  meeteenheid                125655 non-null  object
 12  aanvrager                  125655 non-null  object
 13  alternatief_nummer         125655 non-null  object
 14  motivatie                  125655 non-null  object
 15  geïmpacteerd               125655 non-null  int64
 16  omschrijving               125596 non-null  object
 17  lozingswijze_omschrijving  125655 non-null  object
 18  lozingstype                125655 non-null  object
 19  vha_segment_code           125655 non-null  int64
dtypes: float64(1), int64(8), object(11)
memory usage: 19.2+ MB

,ogc_fid,bedrijfsnaam,id,meetplaats,x_mL72,y_mL72,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,aanvrager,alternatief_nummer,motivatie,geïmpacteerd,omschrijving,lozingswijze_omschrijving,lozingstype,vha_segment_code
0,18314,3M BELGIUM,18314,2070003,147824,213414,2023,2023-09-26,PFUnDS,<,0.025,µg/l,VMM,,emissie meetnet,0,"magnetische debietmeter op effluent, staal op ...",Oppervlaktewater direct,Lozend,6033852
1,18267,3M BELGIUM,18267,2070003,147824,213414,2023,2023-09-26,10:2 FTS,<,0.025,µg/l,VMM,,emissie meetnet,0,"magnetische debietmeter op effluent, staal op ...",Oppervlaktewater direct,Lozend,6033852
2,18268,3M BELGIUM,18268,2070003,147824,213414,2023,2023-09-26,4:2 FTS,<,0.010,µg/l,VMM,,emissie meetnet,0,"magnetische debietmeter op effluent, staal op ...",Oppervlaktewater direct,Lozend,6033852
3,18269,3M BELGIUM,18269,2070003,147824,213414,2023,2023-09-26,6:2 FTS,<,0.010,µg/l,VMM,,emissie meetnet,0,"magnetische debietmeter op effluent, staal op ...",Oppervlaktewater direct,Lozend,6033852
4,18270,3M BELGIUM,18270,2070003,147824,213414,2023,2023-09-26,6:2 diPAP,<,0.025,µg/l,VMM,,emissie meetnet,0,"magnetische debietmeter op effluent, staal op ...",Oppervlaktewater direct,Lozend,6033852

In [ ]:
# Air_dust_VMM
df[17].info()
df[17].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134989 entries, 0 to 134988
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                134989 non-null  int64
 1   code_meetplaats   134989 non-null  object
 2   naam_meetplaats   134989 non-null  object
 3   Straat            134989 non-null  object
 4   Gemeente          134989 non-null  object
 5   Startdatum        134989 non-null  object
 6   Stopdatum         134989 non-null  object
 7   parameter         134989 non-null  object
 8   detectieconditie  134989 non-null  object
 9   waarde            134989 non-null  float64
 10  Eenheid           134989 non-null  object
 11  X                 134989 non-null  float64
 12  Y                 134989 non-null  float64
dtypes: float64(3), int64(1), object(9)
memory usage: 13.4+ MB

,id,code_meetplaats,naam_meetplaats,Straat,Gemeente,Startdatum,Stopdatum,parameter,detectieconditie,waarde,Eenheid,X,Y
0,1176,ZD11,"Zwijndrecht, Blokkersdijk",Zwijndrecht,Canadastraat 13,2025-05-15,2025-05-28,PFHpA,=,0.00500,ng/m³,148200.0,213787.0
1,1176,ZD11,"Zwijndrecht, Blokkersdijk",Zwijndrecht,Canadastraat 13,2025-05-15,2025-05-28,L-PFOA,=,0.07100,ng/m³,148200.0,213787.0
2,1176,ZD11,"Zwijndrecht, Blokkersdijk",Zwijndrecht,Canadastraat 13,2025-05-15,2025-05-28,T-PFOA,=,0.07600,ng/m³,148200.0,213787.0
3,1176,ZD11,"Zwijndrecht, Blokkersdijk",Zwijndrecht,Canadastraat 13,2025-05-15,2025-05-28,PFNA,=,0.00150,ng/m³,148200.0,213787.0
4,1176,ZD11,"Zwijndrecht, Blokkersdijk",Zwijndrecht,Canadastraat 13,2025-05-15,2025-05-28,PFDA,=,0.00083,ng/m³,148200.0,213787.0

In [ ]:
# Air_gas_VMM
df[18].info()
df[18].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13489 entries, 0 to 13488
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                13489 non-null  int64
 1   code_meetplaats   13489 non-null  object
 2   naam_meetplaats   13489 non-null  object
 3   straat            13489 non-null  object
 4   gemeente          13489 non-null  object
 5   Startdatum        13489 non-null  object
 6   Stopdatum         13489 non-null  object
 7   parameter         13489 non-null  object
 8   detectieconditie  13489 non-null  object
 9   waarde            13489 non-null  float64
 10  Eenheid           13489 non-null  object
 11  X                 13489 non-null  int64
 12  Y                 13489 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 1.3+ MB

,id,code_meetplaats,naam_meetplaats,straat,gemeente,Startdatum,Stopdatum,parameter,detectieconditie,waarde,Eenheid,X,Y
0,1,AR05,"Aartselaar, Equans",Aartselaar,Oudestraat 10,2023-09-07,2023-09-20,Totaal PFAS,=,0.0570,ng/m³,151021,203788
1,1,AR05,"Aartselaar, Equans",Aartselaar,Oudestraat 10,2023-09-07,2023-09-20,Som PFAS-20,=,0.0520,ng/m³,151021,203788
2,1,AR05,"Aartselaar, Equans",Aartselaar,Oudestraat 10,2023-09-07,2023-09-20,Som EFSA4,=,0.0120,ng/m³,151021,203788
3,1,AR05,"Aartselaar, Equans",Aartselaar,Oudestraat 10,2023-09-07,2023-09-20,PFBA,=,0.0290,ng/m³,151021,203788
4,1,AR05,"Aartselaar, Equans",Aartselaar,Oudestraat 10,2023-09-07,2023-09-20,PFPeA,<,0.0011,ng/m³,151021,203788

In [ ]:
# Air_deposition_VMM
df[19].info()
df[19].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31723 entries, 0 to 31722
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                31723 non-null  int64
 1   code_meetplaats   31723 non-null  object
 2   naam_meetplaats   31723 non-null  object
 3   straat            31723 non-null  object
 4   gemeente          31723 non-null  object
 5   Startdatum        31723 non-null  object
 6   Stopdatum         31723 non-null  object
 7   parameter         31723 non-null  object
 8   detectieconditie  31723 non-null  object
 9   waarde            31723 non-null  float64
 10  Eenheid           31723 non-null  object
 11  X                 31723 non-null  float64
 12  Y                 31723 non-null  float64
dtypes: float64(3), int64(1), object(9)
memory usage: 3.1+ MB

,id,code_meetplaats,naam_meetplaats,straat,gemeente,Startdatum,Stopdatum,parameter,detectieconditie,waarde,Eenheid,X,Y
0,1,AL01,"Antwerpen, Linkeroever",Antwerpen,Wandeldijk,2021-08-26,2021-09-23,Totaal PFAS,=,7.44,ng/(m².dag),150865.0,214046.0
1,1,AL01,"Antwerpen, Linkeroever",Antwerpen,Wandeldijk,2021-08-26,2021-09-23,Som PFAS-20,=,7.44,ng/(m².dag),150865.0,214046.0
2,1,AL01,"Antwerpen, Linkeroever",Antwerpen,Wandeldijk,2021-08-26,2021-09-23,Som EFSA4,=,2.80,ng/(m².dag),150865.0,214046.0
3,1,AL01,"Antwerpen, Linkeroever",Antwerpen,Wandeldijk,2021-08-26,2021-09-23,PFBA,=,4.20,ng/(m².dag),150865.0,214046.0
4,1,AL01,"Antwerpen, Linkeroever",Antwerpen,Wandeldijk,2021-08-26,2021-09-23,PFPeA,≅,0.00,ng/(m².dag),150865.0,214046.0

In [ ]:
# Combined_groundwater
df[20].info()
df[20].head()

<class 'pandas.core.frame.DataFrame'>
Index: 951050 entries, 0 to 5594
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                951050 non-null  object
 1   datum             951050 non-null  object
 2   x_m_L72           951050 non-null  float64
 3   y_m_L72           951050 non-null  float64
 4   top_m_mv          938735 non-null  float64
 5   basis_m_mv        939079 non-null  float64
 6   parameter         951050 non-null  object
 7   detectieconditie  949483 non-null  object
 8   meetwaarde        951050 non-null  object
 9   meeteenheid       950913 non-null  object
 10  bron              951050 non-null  object
dtypes: float64(4), object(7)
memory usage: 87.1+ MB

,id,datum,x_m_L72,y_m_L72,top_m_mv,basis_m_mv,parameter,detectieconditie,meetwaarde,meeteenheid,bron
0,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,perfluor-n-octaanzuur vertakt (PFOAbranched) (...,<,1,ng/l,pydov
1,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,perfluorheptaansulfonzuur (PFHpS) (PFHpS),<,1,ng/l,pydov
2,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,perfluor-4-ethylcyclohexaansulfonzuur (PFECHS)...,<,1,ng/l,pydov
3,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,6:2/8:2 fluortelomeerfosfaat diester (6:2/8:2 ...,<,10,ng/l,pydov
4,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,totaal perfluor-n-octaanzuur (lineair + vertak...,NaN,2,ng/l,pydov

In [ ]:
# Combined_soil
df[21].info()
df[21].head()

<class 'pandas.core.frame.DataFrame'>
Index: 1155056 entries, 0 to 153055
Data columns (total 11 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   id                1155056 non-null  object
 1   datum             1153183 non-null  object
 2   x_m_L72           1152704 non-null  object
 3   y_m_L72           1152704 non-null  object
 4   top_m_mv          1152676 non-null  float64
 5   basis_m_mv        1152487 non-null  float64
 6   parameter         1155056 non-null  object
 7   detectieconditie  1154904 non-null  object
 8   meetwaarde        1155056 non-null  object
 9   meeteenheid       1155056 non-null  object
 10  bron              1155056 non-null  object
dtypes: float64(2), object(9)
memory usage: 105.7+ MB

,id,datum,x_m_L72,y_m_L72,top_m_mv,basis_m_mv,parameter,detectieconditie,meetwaarde,meeteenheid,bron
0,observatie/2023-37798791,2023-08-29,NaN,NaN,NaN,NaN,perfluornonaansulfonzuur (PFNS) (PFNS),<,0.5,µg/kg ds,pydov
1,observatie/2023-37798785,2023-08-29,NaN,NaN,NaN,NaN,perfluorhexaanzuur (PFHxA) (PFHxA),<,0.5,µg/kg ds,pydov
2,observatie/2023-37798770,2023-08-29,NaN,NaN,NaN,NaN,N-methylperfluorbutaansulfonamide (MePFBSA) (M...,<,0.5,µg/kg ds,pydov
3,observatie/2023-37798774,2023-08-29,NaN,NaN,NaN,NaN,N-methylperfluorbutaansulfonylamide azijnzuur ...,<,0.5,µg/kg ds,pydov
4,observatie/2023-37798786,2023-08-29,NaN,NaN,NaN,NaN,perfluorhexadecaanzuur (PFHxDA) (PFHxDA),<,0.5,µg/kg ds,pydov

In [37]:
# Combined_soil_water
df[22].info()
df[22].head()

<class 'pandas.core.frame.DataFrame'>
Index: 15229 entries, 0 to 15228
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                15229 non-null  int64
 1   datum             15229 non-null  object
 2   x_m_L72           15229 non-null  float64
 3   y_m_L72           15229 non-null  float64
 4   parameter         15229 non-null  object
 5   detectieconditie  15229 non-null  object
 6   meetwaarde        15229 non-null  float64
 7   meeteenheid       15229 non-null  object
 8   bron              15229 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 1.2+ MB

,id,datum,x_m_L72,y_m_L72,parameter,detectieconditie,meetwaarde,meeteenheid,bron
0,32157495,2021-10-08,146312.81,213203.76,PFNS,<,0.20,µg/kg ds,OVAM_sediment
1,32157496,2021-10-08,146312.81,213203.76,PFBA,=,0.82,µg/kg ds,OVAM_sediment
2,32157497,2021-10-08,146312.81,213203.76,PFBSA,<,0.20,µg/kg ds,OVAM_sediment
3,32157498,2021-10-08,146312.81,213203.76,6:2 FTS,<,0.21,µg/kg ds,OVAM_sediment
4,32157499,2021-10-08,146312.81,213203.76,PFDoDS,<,0.32,µg/kg ds,OVAM_sediment

In [38]:
# Combined_surface_water
df[23].info()
df[23].head()

<class 'pandas.core.frame.DataFrame'>
Index: 117106 entries, 0 to 24650
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                117106 non-null  int64
 1   datum             117106 non-null  object
 2   x_m_L72           117106 non-null  float64
 3   y_m_L72           117106 non-null  float64
 4   parameter         117106 non-null  object
 5   detectieconditie  117106 non-null  object
 6   meetwaarde        117106 non-null  float64
 7   meeteenheid       117106 non-null  object
 8   bron              117106 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 8.9+ MB

,id,datum,x_m_L72,y_m_L72,parameter,detectieconditie,meetwaarde,meeteenheid,bron
0,10213,2007-05-31,147328.0,203675.0,PFNA,=,11.0,ng/l,VMM
1,10214,2007-05-31,147328.0,203675.0,PFOA,=,169.0,ng/l,VMM
2,5931,2007-05-31,141077.0,227033.0,PFHpA,=,45.0,ng/l,VMM
3,5932,2007-05-31,141077.0,227033.0,PFNA,=,8.0,ng/l,VMM
4,5933,2007-05-31,141077.0,227033.0,PFOA,=,721.0,ng/l,VMM

### Example 2 : You only want to download the groundwater data of Flanders

In [39]:
medium = ['groundwater']
location = Within(Box(15000, 150000, 270000, 250000, epsg=31370))  # Bounding box Flanders
rd = RequestPFASdata()
df = rd.main(medium, location=location, max_features=None)[0]

2026-02-06 18:05:25.231 | INFO     | PFAS_concentrations:groundwater:520 - Downloading groundwater data

[000/001] .
[000/001] .
[000/001] .
ccccccccccccccccccccccccccccccccccccc
[050/347] cccccccccccccccccccccccccccccccccccccc
[100/347] cccccccccccccccccccccccccccccccccccccc
[150/347] cccccccccccccccccccccccccccccccccccccc
[200/347] ccccccccccccccccccccccccccccccccccccc
[250/347] ccccccccccccccccccccccccccccccccccc
[300/347] ccccccccccccccccccccccccccccccccccc
[000/001] .
[000/001] .

2026-02-06 18:12:00.090 | INFO     | PFAS_concentrations:main:1665 - The program was executed in 0:06:34.859213.

In [40]:
# Groundwater_pydov
df[0].info()
df[0].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12921 entries, 0 to 12920
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pkey_monster             12921 non-null  object
 1   parametergroep           12921 non-null  object
 2   parameter                12921 non-null  object
 3   detectie                 11354 non-null  object
 4   waarde                   12921 non-null  object
 5   eenheid                  12921 non-null  object
 6   methode                  12921 non-null  object
 7   datum_monstername        12921 non-null  datetime64[ns]
 8   pkey_parents             12921 non-null  object
 9   grondwatermonsternummer  12921 non-null  object
 10  pkey_filter              12921 non-null  object
 11  aquifer_code             12921 non-null  object
 12  diepte_onderkant_filter  12104 non-null  float64
 13  lengte_filter            12104 non-null  float64
 14  x                        12921 non-null  float64
 15  y                        12921 non-null  float64
dtypes: datetime64[ns](1), float64(4), object(11)
memory usage: 1.6+ MB

,pkey_monster,parametergroep,parameter,detectie,waarde,eenheid,methode,datum_monstername,pkey_parents,grondwatermonsternummer,pkey_filter,aquifer_code,diepte_onderkant_filter,lengte_filter,x,y
0,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,perfluor-n-octaanzuur vertakt (PFOAbranched) (...,<,1,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9
1,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,perfluorheptaansulfonzuur (PFHpS) (PFHpS),<,1,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9
2,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,perfluor-4-ethylcyclohexaansulfonzuur (PFECHS)...,<,1,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9
3,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,6:2/8:2 fluortelomeerfosfaat diester (6:2/8:2 ...,<,10,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9
4,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,totaal perfluor-n-octaanzuur (lineair + vertak...,NaN,2,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9

In [41]:
# Groundwater_OVAM
df[1].info()
df[1].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 932534 entries, 0 to 932533
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 932534 non-null  int64
 1   opdracht           932534 non-null  int64
 2   pfasdossiernr      932534 non-null  int64
 3   profielnaam        932534 non-null  object
 4   top_in_m           921853 non-null  float64
 5   basis_in_m         921853 non-null  float64
 6   jaar               932534 non-null  int64
 7   datum              932534 non-null  object
 8   parameter          932534 non-null  object
 9   detectieconditie   932534 non-null  object
 10  meetwaarde         932534 non-null  float64
 11  meeteenheid        932397 non-null  object
 12  medium             932534 non-null  object
 13  profieltype        932534 non-null  object
 14  plaatsing_profiel  887892 non-null  object
 15  commentaar         932534 non-null  object
 16  x_ml72             932534 non-null  float64
 17  y_ml72             932534 non-null  float64
dtypes: float64(5), int64(4), object(9)
memory usage: 128.1+ MB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,31063070,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFHpS,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
1,31063071,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFBS,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
2,31063072,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,HFPO-DA,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
3,31063073,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFODA,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
4,31063074,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFBA,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0

In [42]:
# Groundwater_Lantis
df[2].info()
df[2].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5595 entries, 0 to 5594
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectdeel         5595 non-null   object
 1   peilbuis            5595 non-null   object
 2   filter_van_m        4778 non-null   float64
 3   filter_tot_m        5122 non-null   float64
 4   nummer              5595 non-null   int64
 5   analysemonster      5595 non-null   object
 6   datum_bemonstering  5595 non-null   object
 7   gegevens            5595 non-null   object
 8   parameter           5595 non-null   object
 9   detectieconditie    5595 non-null   object
 10  waarde              5595 non-null   float64
 11  eenheid             5595 non-null   object
 12  x_ml72              5595 non-null   float64
 13  y_ml72              5595 non-null   float64
dtypes: float64(5), int64(1), object(8)
memory usage: 612.1+ KB

,projectdeel,peilbuis,filter_van_m,filter_tot_m,nummer,analysemonster,datum_bemonstering,gegevens,parameter,detectieconditie,waarde,eenheid,x_ml72,y_ml72
0,R1O1,PBC3,NaN,14.9,182,PBC3,2022/02/04,RoTS/WiBo,PFHxS,=,5.0,ng/l,154735.956833,213286.10449
1,R1O1,P406,4.1,6.1,88,LD_406,2021/09/23,RoTS/WiBo,8:2 FTS,<,2.0,ng/l,154457.340000,213702.00000
2,KZ,StadAnt_280,3.4,4.4,248,StadAnt_280-1-1 StadAnt_280,2022/01/25,RoTS/Sweco,PFHxDA,<,1.0,ng/l,152803.809990,214595.20000
3,R1O1,P402a,9.1,10.1,77,LD_402a,2021/08/19,RoTS/WiBo,10:2 FTS,<,4.0,ng/l,154374.470000,213884.06000
4,STLO,PFAS-Diep-PB5,21.0,23.0,195,PFAS-Diep-PB5-1-2 PFAS-Diep-PB5,2021/12/08,RoTS/Sweco,PFHxDA,<,1.0,ng/l,149800.908600,214023.70810

### Example 3 : You want to download the soil and groundwater data of Flanders

In [43]:
medium = ['soil', 'groundwater']
location = Within(Box(15000, 150000, 270000, 250000, epsg=31370))  # Bounding box Flanders
rd = RequestPFASdata()
df = rd.main(medium, location=location, max_features=None)[0]

2026-02-06 18:18:00.978 | INFO     | PFAS_concentrations:soil:716 - Downloading soil data

[000/001] .
[000/001] .

/home/roel/Work/DOV/pydov/Code/pydov/contrib/PFAS_concentrations/PFAS_concentrations.py:326: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["pkey_diepteinterval"] = df["pkey_diepteinterval"].fillna(

[000/001] .
[000/002] ..
[000/001] .

2026-02-06 18:25:46.586 | INFO     | PFAS_concentrations:groundwater:520 - Downloading groundwater data

[000/001] .
[000/001] .
[000/001] .
[000/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[050/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[100/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[150/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[200/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[250/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[300/347] ccccccccccccccccccccccccccccccccccccccccccccccc
[000/001] .
[000/001] .

2026-02-06 18:31:43.163 | INFO     | PFAS_concentrations:main:1665 - The program was executed in 0:13:42.185286.

In [44]:
# Soil_OVAM
df[0].info()
df[0].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2353 entries, 0 to 2352
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2353 non-null   object
 1   pkey_parent          2353 non-null   object
 2   parametergroep       2353 non-null   object
 3   parameter            2353 non-null   object
 4   detectieconditie     2201 non-null   object
 5   meetwaarde           2353 non-null   object
 6   eenheid              2353 non-null   object
 7   methode              2353 non-null   object
 8   datum                2353 non-null   object
 9   diepte_van_m         1 non-null      float64
 10  diepte_tot_m         2 non-null      float64
 11  pkey_bodemlocatie    1 non-null      object
 12  pkey_monster         2351 non-null   object
 13  pkey_diepteinterval  0 non-null      float64
 14  x_m_L72              1 non-null      float64
 15  y_m_L72              1 non-null      float64
 16  naam                 1 non-null      object
dtypes: float64(5), object(12)
memory usage: 312.6+ KB

,id,pkey_parent,parametergroep,parameter,detectieconditie,meetwaarde,eenheid,methode,datum,diepte_van_m,diepte_tot_m,pkey_bodemlocatie,pkey_monster,pkey_diepteinterval,x_m_L72,y_m_L72,naam
0,observatie/2023-37798791,monster/2023-376712,Bodem_chemisch_PFAS,perfluornonaansulfonzuur (PFNS) (PFNS),<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN
1,observatie/2023-37798785,monster/2023-376712,Bodem_chemisch_PFAS,perfluorhexaanzuur (PFHxA) (PFHxA),<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN
2,observatie/2023-37798770,monster/2023-376712,Bodem_chemisch_PFAS,N-methylperfluorbutaansulfonamide (MePFBSA) (M...,<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN
3,observatie/2023-37798774,monster/2023-376712,Bodem_chemisch_PFAS,N-methylperfluorbutaansulfonylamide azijnzuur ...,<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN
4,observatie/2023-37798786,monster/2023-376712,Bodem_chemisch_PFAS,perfluorhexadecaanzuur (PFHxDA) (PFHxDA),<,0.5,µg/kg ds,PFAS in bodem volgens CMA_3_D,2023-08-29,NaN,NaN,NaN,monster/2023-376712,NaN,NaN,NaN,NaN

In [45]:
# Soil_Lantis
df[1].info()
df[1].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003099 entries, 0 to 1003098
Data columns (total 18 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id                 1003099 non-null  int64
 1   opdracht           1003099 non-null  int64
 2   pfasdossiernr      1003099 non-null  int64
 3   profielnaam        1003099 non-null  object
 4   top_in_m           1003099 non-null  float64
 5   basis_in_m         1003099 non-null  float64
 6   jaar               1003099 non-null  int64
 7   datum              1003099 non-null  object
 8   parameter          1003099 non-null  object
 9   detectieconditie   1003099 non-null  object
 10  meetwaarde         1003099 non-null  float64
 11  meeteenheid        1003099 non-null  object
 12  medium             1003099 non-null  object
 13  profieltype        1003099 non-null  object
 14  plaatsing_profiel  937826 non-null   object
 15  commentaar         1003099 non-null  object
 16  x_ml72             1003099 non-null  float64
 17  y_ml72             1003099 non-null  float64
dtypes: float64(5), int64(4), object(9)
memory usage: 137.8+ MB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,31063144,13077062,6180,108,0.5,0.7,2021,2021-06-01,PFHxStotaal,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0
1,31063147,13077062,6180,108,0.5,0.7,2021,2021-06-01,PFPeA,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0
2,31063151,13077062,6180,108,0.5,0.7,2021,2021-06-01,8:2 diPAP,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0
3,31063157,13077062,6180,108,0.5,0.7,2021,2021-06-01,PFPeS,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0
4,31063159,13077062,6180,108,0.5,0.7,2021,2021-06-01,PFNS,<,0.2,µg/kg ds,Vaste deel van de aarde,Boring,2021-05-21,,237521.0,204927.0

In [46]:
# Groundwater_pydov
df[2].info()
df[2].head()

<class 'pandas.core.frame.DataFrame'>
Index: 149604 entries, 0 to 153055
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   boring              149604 non-null  object
 1   diepte_van_m        149576 non-null  float64
 2   diepte_tot_m        149386 non-null  float64
 3   unieke_monstercode  149604 non-null  object
 4   analysemonster      149604 non-null  object
 5   datum_bemonstering  147731 non-null  object
 6   gegevens            149604 non-null  object
 7   parameter           149604 non-null  object
 8   detectieconditie    149604 non-null  object
 9   waarde              149604 non-null  float64
 10  eenheid             149604 non-null  object
 11  x_ml72              149604 non-null  object
 12  y_ml72              149604 non-null  object
dtypes: float64(3), object(10)
memory usage: 16.0+ MB

,boring,diepte_van_m,diepte_tot_m,unieke_monstercode,analysemonster,datum_bemonstering,gegevens,parameter,detectieconditie,waarde,eenheid,x_ml72,y_ml72
0,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,totaal PFAS,=,0.0,µg/kg ds,148378.16,211294.01
1,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,totaal PFAS kwantitatief,<,0.5,µg/kg ds,148378.16,211294.01
2,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,totaal PFAS indicatief,<,1.0,µg/kg ds,148378.16,211294.01
3,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,som PFOA,<,0.5,µg/kg ds,148378.16,211294.01
4,ZW_22B,0.02,0.03,ZW_22B(2.5-3),ZW_22B,03/10/2022,THV RoTS,som PFOS,<,0.5,µg/kg ds,148378.16,211294.01

In [47]:
# Groundwater_OVAM
df[3].info()
df[3].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12921 entries, 0 to 12920
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pkey_monster             12921 non-null  object
 1   parametergroep           12921 non-null  object
 2   parameter                12921 non-null  object
 3   detectie                 11354 non-null  object
 4   waarde                   12921 non-null  object
 5   eenheid                  12921 non-null  object
 6   methode                  12921 non-null  object
 7   datum_monstername        12921 non-null  datetime64[ns]
 8   pkey_parents             12921 non-null  object
 9   grondwatermonsternummer  12921 non-null  object
 10  pkey_filter              12921 non-null  object
 11  aquifer_code             12921 non-null  object
 12  diepte_onderkant_filter  12104 non-null  float64
 13  lengte_filter            12104 non-null  float64
 14  x                        12921 non-null  float64
 15  y                        12921 non-null  float64
dtypes: datetime64[ns](1), float64(4), object(11)
memory usage: 1.6+ MB

,pkey_monster,parametergroep,parameter,detectie,waarde,eenheid,methode,datum_monstername,pkey_parents,grondwatermonsternummer,pkey_filter,aquifer_code,diepte_onderkant_filter,lengte_filter,x,y
0,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,perfluor-n-octaanzuur vertakt (PFOAbranched) (...,<,1,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9
1,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,perfluorheptaansulfonzuur (PFHpS) (PFHpS),<,1,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9
2,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,perfluor-4-ethylcyclohexaansulfonzuur (PFECHS)...,<,1,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9
3,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,6:2/8:2 fluortelomeerfosfaat diester (6:2/8:2 ...,<,10,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9
4,https://oefen.dov.vlaanderen.be/data/monster/2...,Grondwater_chemisch_PFAS,totaal perfluor-n-octaanzuur (lineair + vertak...,NaN,2,ng/l,Onbekend,2022-02-02,(https://oefen.dov.vlaanderen.be/data/filter/2...,25(483/21/9_1 | 01/02/22 - 30/06/22),https://oefen.dov.vlaanderen.be/data/filter/20...,A0170,2.5,0.5,120742.5,192166.9

In [48]:
# Groundwater_Lantis
df[4].info()
df[4].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 932534 entries, 0 to 932533
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 932534 non-null  int64
 1   opdracht           932534 non-null  int64
 2   pfasdossiernr      932534 non-null  int64
 3   profielnaam        932534 non-null  object
 4   top_in_m           921853 non-null  float64
 5   basis_in_m         921853 non-null  float64
 6   jaar               932534 non-null  int64
 7   datum              932534 non-null  object
 8   parameter          932534 non-null  object
 9   detectieconditie   932534 non-null  object
 10  meetwaarde         932534 non-null  float64
 11  meeteenheid        932397 non-null  object
 12  medium             932534 non-null  object
 13  profieltype        932534 non-null  object
 14  plaatsing_profiel  887892 non-null  object
 15  commentaar         932534 non-null  object
 16  x_ml72             932534 non-null  float64
 17  y_ml72             932534 non-null  float64
dtypes: float64(5), int64(4), object(9)
memory usage: 128.1+ MB

,id,opdracht,pfasdossiernr,profielnaam,top_in_m,basis_in_m,jaar,datum,parameter,detectieconditie,meetwaarde,meeteenheid,medium,profieltype,plaatsing_profiel,commentaar,x_ml72,y_ml72
0,31063070,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFHpS,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
1,31063071,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFBS,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
2,31063072,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,HFPO-DA,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
3,31063073,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFODA,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0
4,31063074,13077062,6180,PB31,0.2,2.2,2021,2021-06-16,PFBA,<,0.02,µg/l,Grondwater,Peilbuis,NaN,,237529.0,204908.0

### Example 4 : You want to download the combined groundwater PFAS data of Flanders

In [49]:
medium = ['combined_groundwater']
location = Within(Box(15000, 150000, 270000, 250000, epsg=31370))  # Bounding box Flanders
rd = RequestPFASdata()
df = rd.main(medium, location=location, max_features=None)[0]

2026-02-06 18:58:06.086 | INFO     | PFAS_concentrations:groundwater:520 - Downloading groundwater data

[000/001] .
[000/001] .
[000/001] .
[000/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[050/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[100/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[150/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[200/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[250/347] cccccccccccccccccccccccccccccccccccccccccccccccccc
[300/347] ccccccccccccccccccccccccccccccccccccccccccccccc
[000/001] .
[000/001] .

2026-02-06 19:04:29.225 | INFO     | PFAS_concentrations:main:1665 - The program was executed in 0:06:23.144295.

In [50]:
# combined_groundwater
df[0].info()
df[0].head()

<class 'pandas.core.frame.DataFrame'>
Index: 951050 entries, 0 to 5594
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                951050 non-null  object
 1   datum             951050 non-null  object
 2   x_m_L72           951050 non-null  float64
 3   y_m_L72           951050 non-null  float64
 4   top_m_mv          938735 non-null  float64
 5   basis_m_mv        939079 non-null  float64
 6   parameter         951050 non-null  object
 7   detectieconditie  949483 non-null  object
 8   meetwaarde        951050 non-null  object
 9   meeteenheid       950913 non-null  object
 10  bron              951050 non-null  object
dtypes: float64(4), object(7)
memory usage: 87.1+ MB

,id,datum,x_m_L72,y_m_L72,top_m_mv,basis_m_mv,parameter,detectieconditie,meetwaarde,meeteenheid,bron
0,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,perfluor-n-octaanzuur vertakt (PFOAbranched) (...,<,1,ng/l,pydov
1,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,perfluorheptaansulfonzuur (PFHpS) (PFHpS),<,1,ng/l,pydov
2,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,perfluor-4-ethylcyclohexaansulfonzuur (PFECHS)...,<,1,ng/l,pydov
3,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,6:2/8:2 fluortelomeerfosfaat diester (6:2/8:2 ...,<,10,ng/l,pydov
4,25(483/21/9_1 | 01/02/22 - 30/06/22),2022-02-02 00:00:00,120742.5,192166.9,2.0,2.5,totaal perfluor-n-octaanzuur (lineair + vertak...,NaN,2,ng/l,pydov