# Example of DOV search methods for quartaire stratigrafie

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/DOV-Vlaanderen/pydov/master?filepath=docs%2Fnotebooks%2Fsearch_quartaire_stratigrafie.ipynb)

## Use cases:
* Select records in a bbox
* Select records in a bbox with selected properties
* Select records within a distance from a point
* Select records in a municipality
* Get records using info from wfs fields, not available in the standard output dataframe

In [1]:
%matplotlib inline
import os, sys
import inspect

In [2]:
# check pydov path
import pydov

## Get information about code base

In [3]:
from pydov.search.interpretaties import QuartairStratigrafieSearch
# information about the QuartairStratigrafie type (In Dutch):
ip_quart = QuartairStratigrafieSearch()
ip_quart.get_description()

'De quartaire afzettingen in Vlaanderen, de jongste afzettingen, zijn lateraal en verticaal heterogeen en varieren erg in dikte. De afzettingen zijn vooral onder continentale omstandigheden tot stand gekomen (rivier-, duinafzettingen). Eigenlijk zijn het pakketten die zelden meer dan 30 meter en soms zelfs minder dan 1 meter dik zijn. Omwille van deze grote eigenheid en de grote mate van detail van de beschrijvingen, werd hiervoor een eigen stratigrafische codering uitgewerkt voor Vlaanderen.'

In [4]:
# information about the available fields for a QuartairStratigrafie object
fields = ip_quart.get_fields()
# print available fields
for f in fields.values():
    print(f['name'])

pkey_interpretatie
Type_proef
Proefnummer
pkey_boring
x
y
start_interpretatie_mtaw
diepte_tot_m
gemeente
Auteurs
Datum
Opdrachten
betrouwbaarheid_interpretatie
Geldig_van
Geldig_tot
eerste_invoer
geom
diepte_laag_van
diepte_laag_tot
lid1
relatie_lid1_lid2
lid2

In [5]:
# print information for a certain field
fields['Type_proef']

{'name': 'Type_proef', 'definition': "Het type van de proef waarvan de quartaire stratigrafie een interpretatie is. Bij een quartaire stratigrafie zal dit altijd 'Boring' zijn.", 'type': 'string', 'multivalue': False, 'notnull': False, 'query': True, 'cost': 1, 'codelist': <pydov.util.codelists.AbstractCodeList: <pydov.util.codelists.CodeListItem: code: Boring, label: Boring, definition: De quartaire stratigrafie is een interpretatie van een boring.>>}

The cost is an arbitrary attribute to indicate if the information is retrieved from a wfs query (cost = 1), 
or from an xml (cost = 10)

Alternatively, you can list all the fields and their details by inspecting the `get_fields()` output or the search instance itself in a notebook:

In [6]:
ip_quart

## Try-out of use cases

### Select interpretations in a bbox

In [16]:
from pydov.util.location import Within, Box

# Get all interpretations in a bounding box (llx, lly, ulx, uly)
# the pkey_boring link is not available below, but is in the df
df = ip_quart.search(location=Within(Box(132815, 191700, 133815, 192700, epsg=31370)))

df['lid1_label'] = df['lid1'].apply(ip_quart.get_fields().lid1.codelist.get_definition)
df['lid2_label'] = df['lid2'].apply(ip_quart.get_fields().lid2.codelist.get_definition)

df = df[['pkey_interpretatie', 'pkey_boring', 'betrouwbaarheid_interpretatie', 'x', 'y',
         'start_interpretatie_mtaw', 'diepte_laag_van', 'diepte_laag_tot', 'lid1', 'lid1_label',
         'relatie_lid1_lid2', 'lid2', 'lid2_label']]

df.head()

[000/001] .
[000/003] cc

,pkey_interpretatie,pkey_boring,betrouwbaarheid_interpretatie,x,y,start_interpretatie_mtaw,diepte_laag_van,diepte_laag_tot,lid1,lid1_label,relatie_lid1_lid2,lid2,lid2_label
0,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132975.0,191969.0,2.84,0.0,4.5,K,"Holoceen, continentaal alluvium-grof facies",T,K,"Holoceen, continentaal alluvium-grof facies"
1,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132975.0,191969.0,2.84,4.5,7.5,F,"Weichseliaan, continentaal, fluviatiel, perigl...",T,F,"Weichseliaan, continentaal, fluviatiel, perigl..."
2,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132975.0,191969.0,2.84,7.5,8.0,Rf,Grindrijk zand - puinwaaier,T,Rf,Grindrijk zand - puinwaaier
3,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132949.0,192068.0,2.57,0.0,4.5,K,"Holoceen, continentaal alluvium-grof facies",T,K,"Holoceen, continentaal alluvium-grof facies"
4,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132949.0,192068.0,2.57,4.5,9.5,F,"Weichseliaan, continentaal, fluviatiel, perigl...",T,F,"Weichseliaan, continentaal, fluviatiel, perigl..."

### Select interpretations in a bbox with selected properties

In [8]:
# list available query methods
methods = [i for i,j in inspect.getmembers(sys.modules['owslib.fes2'], 
                                           inspect.isclass) 
           if 'Property' in i]
methods

['PropertyIsBetween',
 'PropertyIsEqualTo',
 'PropertyIsGreaterThan',
 'PropertyIsGreaterThanOrEqualTo',
 'PropertyIsLessThan',
 'PropertyIsLessThanOrEqualTo',
 'PropertyIsLike',
 'PropertyIsNotEqualTo',
 'PropertyIsNull',
 'SortProperty']

In [9]:
from owslib.fes2 import PropertyIsGreaterThanOrEqualTo

The property feature methodes listed above are available from the owslib module. These were not adapted for use in pydov.

In [17]:
# Get deep boreholes in a bounding box 
from owslib.fes2 import PropertyIsLike
# the propertyname can be any of the fields of the interpretations object that belong to the wfs source
# the literal is always a string, no matter what its definition is in the boring object (string, float...)
query = PropertyIsLike(
        propertyname='betrouwbaarheid_interpretatie', literal='onbekend')
df = ip_quart.search(location=Within(Box(132815, 191700, 133815, 192700, epsg=31370)),
                     query=query
                    )

df['lid1_label'] = df['lid1'].apply(ip_quart.get_fields().lid1.codelist.get_definition)
df['lid2_label'] = df['lid2'].apply(ip_quart.get_fields().lid2.codelist.get_definition)

df = df[['pkey_interpretatie', 'pkey_boring', 'betrouwbaarheid_interpretatie', 'x', 'y',
         'start_interpretatie_mtaw', 'diepte_laag_van', 'diepte_laag_tot', 'lid1', 'lid1_label',
         'relatie_lid1_lid2', 'lid2', 'lid2_label']]

df.head()

[000/001] .
[000/003] cc

,pkey_interpretatie,pkey_boring,betrouwbaarheid_interpretatie,x,y,start_interpretatie_mtaw,diepte_laag_van,diepte_laag_tot,lid1,lid1_label,relatie_lid1_lid2,lid2,lid2_label
0,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132975.0,191969.0,2.84,0.0,4.5,K,"Holoceen, continentaal alluvium-grof facies",T,K,"Holoceen, continentaal alluvium-grof facies"
1,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132975.0,191969.0,2.84,4.5,7.5,F,"Weichseliaan, continentaal, fluviatiel, perigl...",T,F,"Weichseliaan, continentaal, fluviatiel, perigl..."
2,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132975.0,191969.0,2.84,7.5,8.0,Rf,Grindrijk zand - puinwaaier,T,Rf,Grindrijk zand - puinwaaier
3,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132949.0,192068.0,2.57,0.0,4.5,K,"Holoceen, continentaal alluvium-grof facies",T,K,"Holoceen, continentaal alluvium-grof facies"
4,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1974...,onbekend,132949.0,192068.0,2.57,4.5,9.5,F,"Weichseliaan, continentaal, fluviatiel, perigl...",T,F,"Weichseliaan, continentaal, fluviatiel, perigl..."

### Select records within a distance from a point

In [18]:
from pydov.util.location import Point, WithinDistance

# Get all interpretations within a defined distance from a point
location = WithinDistance(location=Point(133000, 192000, epsg=31370),
                          distance=1000, distance_unit='meter')
df = ip_quart.search(location=location)

df['lid1_label'] = df['lid1'].apply(ip_quart.get_fields().lid1.codelist.get_definition)
df['lid2_label'] = df['lid2'].apply(ip_quart.get_fields().lid2.codelist.get_definition)

df = df[['pkey_interpretatie', 'pkey_boring', 'betrouwbaarheid_interpretatie', 'x', 'y',
         'start_interpretatie_mtaw', 'diepte_laag_van', 'diepte_laag_tot', 'lid1', 'lid1_label',
         'relatie_lid1_lid2', 'lid2', 'lid2_label']]

df.head()

[000/001] .
[000/015] ccccccccccccccc

,pkey_interpretatie,pkey_boring,betrouwbaarheid_interpretatie,x,y,start_interpretatie_mtaw,diepte_laag_van,diepte_laag_tot,lid1,lid1_label,relatie_lid1_lid2,lid2,lid2_label
0,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1943...,onbekend,132035.0,191802.0,3.14,0.0,1.5,K,"Holoceen, continentaal alluvium-grof facies",T,K,"Holoceen, continentaal alluvium-grof facies"
1,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1943...,onbekend,132035.0,191802.0,3.14,1.5,2.5,D,Weichseliaan continentaal eolisch-grof facies,T,D,Weichseliaan continentaal eolisch-grof facies
2,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1943...,onbekend,132035.0,191802.0,3.14,2.5,11.5,F,"Weichseliaan, continentaal, fluviatiel, perigl...",T,Rf,Grindrijk zand - puinwaaier
3,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1943...,onbekend,132035.0,191802.0,3.14,11.5,30.0,$,Tertiair,T,$,Tertiair
4,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1943...,onbekend,132066.0,191830.0,3.15,0.0,2.0,K,"Holoceen, continentaal alluvium-grof facies",T,K,"Holoceen, continentaal alluvium-grof facies"

### Select interpretations in a municipality

In [19]:
from owslib.fes2 import PropertyIsEqualTo
query = PropertyIsEqualTo(propertyname='gemeente',
                          literal='Hamme')
df = ip_quart.search(query=query)

df['lid1_label'] = df['lid1'].apply(ip_quart.get_fields().lid1.codelist.get_definition)
df['lid2_label'] = df['lid2'].apply(ip_quart.get_fields().lid2.codelist.get_definition)

df = df[['pkey_interpretatie', 'pkey_boring', 'betrouwbaarheid_interpretatie', 'x', 'y',
         'start_interpretatie_mtaw', 'diepte_laag_van', 'diepte_laag_tot', 'lid1', 'lid1_label',
         'relatie_lid1_lid2', 'lid2', 'lid2_label']]

df.head()

[000/001] .
[000/024] ccccccccccccc

,pkey_interpretatie,pkey_boring,betrouwbaarheid_interpretatie,x,y,start_interpretatie_mtaw,diepte_laag_van,diepte_laag_tot,lid1,lid1_label,relatie_lid1_lid2,lid2,lid2_label
0,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1895...,onbekend,129384.0,197648.0,6.0,0.0,2.7,f1,"Weichseliaan, continentaal, fluviatiel, perigl...",T,f1,"Weichseliaan, continentaal, fluviatiel, perigl..."
1,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1895...,onbekend,128641.0,197803.0,5.0,0.0,2.8,F,"Weichseliaan, continentaal, fluviatiel, perigl...",T,F,"Weichseliaan, continentaal, fluviatiel, perigl..."
2,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1894...,goed,128930.0,198740.0,4.0,0.0,12.2,F,"Weichseliaan, continentaal, fluviatiel, perigl...",T,F,"Weichseliaan, continentaal, fluviatiel, perigl..."
3,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1894...,goed,128930.0,198740.0,4.0,12.2,20.4,$,Tertiair,T,$,Tertiair
4,https://www.dov.vlaanderen.be/data/interpretat...,https://www.dov.vlaanderen.be/data/boring/1894...,goed,129770.0,198680.0,4.6,0.0,3.5,F,"Weichseliaan, continentaal, fluviatiel, perigl...",T,F,"Weichseliaan, continentaal, fluviatiel, perigl..."

### Visualize results

Using Folium, we can display the results of our search on a map.

In [22]:
# import the necessary modules (not included in the requirements of pydov!)
import folium
from folium.plugins import MarkerCluster
from pyproj import Transformer

In [23]:
# convert the coordinates to lat/lon for folium
def convert_latlon(x1, y1):
    transformer = Transformer.from_crs("epsg:31370", "epsg:4326", always_xy=True)
    x2,y2 = transformer.transform(x1, y1)
    return x2, y2

df['lon'], df['lat'] = zip(*map(convert_latlon, df['x'], df['y'])) 
# convert to list
loclist = df[['lat', 'lon']].values.tolist()

In [24]:
# initialize the Folium map on the centre of the selected locations, play with the zoom until ok
fmap = folium.Map(location=[df['lat'].mean(), df['lon'].mean()], zoom_start=12)
marker_cluster = MarkerCluster().add_to(fmap)
for loc in range(0, len(loclist)):
    folium.Marker(loclist[loc], popup=df['lid1'][loc]).add_to(marker_cluster)
fmap